{
 "title": "Basic Monitoring Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Total RAG Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rag_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "RAG Average Latency",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(rag_duration_seconds_sum[5m])\r\n/\r\nrate(rag_duration_seconds_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAG Errors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rag_errors_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "RAG Requests / Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    { "expr": "rate(rag_requests_total[5m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Input Tokens",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "llm_input_tokens_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Output Token",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "llm_output_tokens_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Output Tokens per Request",
   "type": "stat",
   "gridPos": { "h": 16, "w": 10, "x": 14, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(llm_input_tokens_total[5m])\r\n/\r\nrate(rag_requests_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Tokens",
   "type": "stat",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "llm_total_tokens_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Positive Feedback %",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\r\nrag_feedback_useful_total\r\n/\r\n(\r\n  rag_feedback_useful_total\r\n  +\r\n  rag_feedback_not_useful_total\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Useful vs Not Useful Feedbacks",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rag_feedback_useful_total", "legendFormat": "__auto" },
    { "expr": "rag_feedback_not_useful_total", "legendFormat": "__auto" }
   ]
  }
 ]
}