[project]
name = "movie-assistant"
version = "0.1.0"
description = "2016 - 2026 Movie Assistant RAG"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "minsearch>=0.1.0",
    "openai>=2.41.0",
    "opentelemetry-api>=1.44.0",
    "opentelemetry-exporter-otlp-proto-grpc>=1.44.0",
    "opentelemetry-exporter-prometheus>=0.65b0",
    "opentelemetry-sdk>=1.44.0",
    "pandas>=3.0.3",
    "python-dotenv>=1.2.2",
    "requests>=2.34.2",
    "scikit-learn>=1.9.0",
    "sentence-transformers>=5.6.0",
    "streamlit>=1.59.2",
    "tqdm>=4.68.2",
    "prometheus-client"
]

[tool.uv.sources]
torch = { index = "pytorch-cpu" }

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true