from opentelemetry import trace, metrics
from opentelemetry.sdk.trace import TracerProvider
from opentelemetry.sdk.trace.export import (BatchSpanProcessor, ConsoleSpanExporter)

from opentelemetry.sdk.metrics import MeterProvider
from opentelemetry.sdk.metrics.export import (ConsoleMetricExporter, PeriodicExportingMetricReader)

from opentelemetry.exporter.otlp.proto.grpc.trace_exporter import (OTLPSpanExporter)

from prometheus_client import start_http_server
from opentelemetry.exporter.prometheus import PrometheusMetricReader

#-----EXPORTER-----#
otlp_exporter= OTLPSpanExporter(endpoint="http://tempo:4317", insecure=True)

#-----TRACING-----#
provider = TracerProvider()

processor = BatchSpanProcessor(ConsoleSpanExporter())

provider.add_span_processor(processor)
trace.set_tracer_provider(provider)
tracer=trace.get_tracer("movie-assistant")

provider.add_span_processor(BatchSpanProcessor(otlp_exporter))

#-----METRICS-----#

start_http_server(
    port=9464,
    addr="0.0.0.0"
)

metric_reader= PrometheusMetricReader()
metric_provider= MeterProvider(metric_readers=[metric_reader])

metrics.set_meter_provider(metric_provider)
meter=metrics.get_meter("movie-assistant")

rag_requests= meter.create_counter("rag_requests_total", description="Total number of RAG requests")
rag_errors = meter.create_counter("rag_errors_total", description="Total numer of RAG errors")
rag_duration= meter.create_histogram("rag_duration_seconds", description="RAG request duration in seconds")

llm_input_tokens = meter.create_counter("llm_input_tokens_total", description="Total number of input tokens used by the LLM")
llm_output_tokens = meter.create_counter("llm_output_tokens_total", description="Total number of output tokens generated by the LLM")
llm_total_tokens = meter.create_counter("llm_total_tokens_total", description="Total number of tokens used by the LLM")

feedback_useful = meter.create_counter("rag_feedback_useful_total", description="Number of positive user feedback responses")
feedback_not_useful = meter.create_counter("rag_feedback_not_useful_total", description="Number of negative user feedback responses")


